### ISSUE TITLE
"rwx" rights in studyfolder /NENAH_BIDS 

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#108]
We need to look at "rwx" on study folder /NENAH_BIDS and its subfolder

**Comment by yukaizou2015** [comment]
One way to solve this issue is to run the following commands after running docker:
```
chown -R :neuropediatrics /target/dir
chmod -R g+rw /target/dir
```
This will change permission of the subsequent folder and subfolders under `neuropediatrics`, and grant read and write permissions to the group users.

**Comment by yukaizou2015** [comment]
Another solution would be to use `setfacl` and `getfacl`

**Comment by finnlennartsson** [comment]
Not relevant anymore
