### ISSUE TITLE
Creating slice_timings in json

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#12]
Need to understand how the DCM-conversion is and if we need to supplement data. 

Comes back to the `dcm2niix` conversion. Normally, `dcm2niix` can convert and add appropriate `slice_timings` to the `.json`-file. 
Now, DCM is exported and anonymised using Syngovia - this might mean that certain DCM-tags disappear?

E.g. create a slice_order file as input to EDDY. This is normally automatically generated from slice timings when providing eddy with the .json-file as input. 

See [EDDY documentation](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#A--slspec):
"For single-band data and for multi-band data (not NENAH case) with an odd number of excitations/MB-groups it is trivial to work out the `--slspec` file using the logic of the example. For an even number of excitations/MB-groups it is considerably more difficult and we recommend using a DICOM->niftii converter that writes the exact slice timings into a .JSON file. This can then be used to create the `--slspec` file."

**Comment by yukaizou2015** [comment]
An example: 

sub-NENAHC001_dir-AP_run-1_dwi.json:
```
"SliceTiming": [0.00464, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001, -0.001]
```

sub-NENAHC001_task-rest_dir-AP_run-1_bold.json
```
"SliceTiming": [0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075, 0.001075]
```

**Comment by yukaizou2015** [comment]
`mrinfo -json_keyval filename.json dirname/`

**To do**: read in json file from BIDS conversion, and amend `SliceTiming` with output from `mrinfo`.

Created a new branch `slice_timings`. Code can be found here:

https://github.com/yukaizou2015/NENAH-BIDS/blob/1080cc58bacf8432def3b64e68e7897c3a8c03d8/replace_slicetimings.ipynb

Next is to clean up & apply to all the cases, merge the cleaned code to `main` via pull request.

**Comment by yukaizou2015** [comment]
All updated json files are named as `*_dwi_SliceTimings_updated.json` and can be found at `/local/scratch/disk2/research/NENAH_BIDS/derivatives/slice_timings`

**Comment by yukaizou2015** [comment]
Newly identified in #69, that the .json file for fieldmaps also need to be updated.

**Comment by finnlennartsson** [comment]
Probably not relevant anymore
