### ISSUE TITLE
NVIDIA on WS RHEL8

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#152]
After the upgrade to RHEL8, the NVIDIA card does not seem to be installed properly. 

The current graphics card is not the NVIDIA
![image](https://user-images.githubusercontent.com/20419258/225524694-157f6853-46a1-4d4b-bae8-a40d422f9fc9.png)

Perhaps instructions from here can be used
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#

**Comment by nayanw775** [comment]
Old instructions from Kai for installing a  docker are expired and seem to be not working, looking for a new solution. The ticket he raised with ISolutions not seems to be working too. Nayan, raised a new ticket with ISolutions for giving root permissions, docker needs root permissions for the installation.

**Comment by finnlennartsson** [comment]
We don't need to install CUDA anymore. https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/GPU

In new releases of FSL, the toolkit is statically linked into the executable files, so all that is needed to run them is a NVIDIA GPU and CUDA driver that suppports CUDA 10.2 or newer - you do not need to install the CUDA Toolkit in order to run these tools
