### ISSUE TITLE
Transform csd into _space-anat and do tractography etc in this space 

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#163]

**Comment by RioPhillips** [comment]
Added a script to perform this transformation (it sits in my branch dMRI/dwi_to_anat.sh), was unsure whether the 5TT-files should be kept in dwi-space. 

Utilized -reorient_fod as talked about last meeting.

**Comment by finnlennartsson** [comment]
5TT should be in space-anat

My suggestion is 
1. to add a line in the end of dMRI/csd.sh where you re-orient the csd like you do in dMRI/dwi_to_anat.sh
2. add section in dMRI/5tt.sh where to replicate this but in anat-space
https://github.com/sotnir/NENAH-BIDS/blob/70ffd2c97be0cd5e08f79554612e7ef5667ebcdd/dMRI/5tt.sh#L76-L99
