### ISSUE TITLE
MRtrix

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#18]
- latest (via conda): https://www.mrtrix.org/download/linux-anaconda/

**Comment by yukaizou2015** [comment]
## SHARD
 - [Diffusion SHARD Pipeline](https://biomedia.github.io/dHCP-release-notes/dwi-shard.html)

Do a source install following [this instruction](https://mrtrix.readthedocs.io/en/latest/installation/build_from_source.html) to install the [shard-recon](https://github.com/dchristiaens/shard-recon) module to look into #68 
 - (17 Nov 2021) Require `GCC >= 5`. Follow instructions [here](http://linuxdesktops.soton.ac.uk/c.html) to update GCC (default version 4.8.5):
```
yum install devtoolset-4-gcc devtoolset-4-gcc-c++
scl enable devtoolset-4 bash
```
 - (Important) Install Qt5 `v5.5.0` ([archive](https://download.qt.io/new_archive/qt/))
```
./configure -prefix $PWD/qtbase -opensource -qt-xcb
make -j8
```

Update `.bashrc` by adding the following lines:
```
export PATH=/local/scratch/software/qt-everywhere-opensource-src-5.5.0/qtbase/bin:$PATH
export MESA_GL_VERSION_OVERRIDE=3.3 # to launch mrview in remote desktop
```

**Comment by yukaizou2015** [comment]
To launch `mrview` in remote desktop, type
```
export MESA_GL_VERSION_OVERRIDE=3.3
```

**Comment by yukaizou2015** [comment]
Having issue installing `Qt5` at the moment.

On MRtrix documentation it states that `Qt version >= 5.5` (but not Qt 6) is required.

Qt version 5.9.0+ no longer ship fonts, and launched an mrview GUI without any text:
```
QFontDatabase: Cannot find font directory /local/scratch/software/qt-everywhere-opensource-src-5.9.9/qtbase/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
```

**Comment by yukaizou2015** [comment]
After installing Qt `v5.5.0` mrview GUI can be launched with text loaded successfully.

**Comment by finnlennartsson** [comment]
MRtrix is working fine on the NEW UoS Workstation
