### ISSUE TITLE
dcm2niix

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#19]
- (19 Nov 2021) Built from source
 - https://github.com/rordenlab/dcm2niix
Add path to `.bashrc`:
```
export PATH=/local/scratch/software/dcm2niix/build/bin:$PATH
```

**Comment by finnlennartsson** [comment]
Reinstalled by Nayan after upgrade to RHEL8
Followed instructions above
add to path
`export PATH=/local/scratch/software/dcm2niix/build/bin:$PATH`
