### ISSUE TITLE
P5_syngo_test_dMRI dwifslpreproc

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#24]
There is some slice-to-volume movement.

![pastedImage](https://user-images.githubusercontent.com/12237727/104441494-aad78c00-558b-11eb-876d-275ab6c135f2.png)

Suspect that the b0APPA that was put in in the end was faulty. Now taken two proper opposite PE-directions.

![pastedImage](https://user-images.githubusercontent.com/12237727/104441576-c773c400-558b-11eb-8fea-bb68e4cf7108.png)

![pastedImage](https://user-images.githubusercontent.com/12237727/104441595-cc387800-558b-11eb-8332-ef4a7638a1df.png)

 - Task: learn to distinguish different PE-directions.

**Comment by yukaizou2015** [comment]
NENAH010 - #5

**Comment by finnlennartsson** [comment]
No relevant anymore
