### ISSUE TITLE
bids format for subject with repeated scans / taken out of scanner

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#25]
- [BIDS principle](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html)
      - _"Session can (but doesn't have to) be synonymous to a visit in a longitudinal study. In general, subjects will stay in the scanner during one session. However, for example, if a subject has to leave the scanner room and then be re-positioned on the scanner bed, the set of MRI acquisitions will still be considered as a session and match sessions acquired in other subjects. Similarly, in situations where different data types are obtained over several visits (for example fMRI on one day followed by DWI the day after) those can be grouped in one session. Defining multiple sessions is appropriate when several identical or similar data acquisitions are planned and performed on all -or most- subjects, often in the case of some intervention between sessions (for example, training)."_
 - Also see: https://neurostars.org/t/subject-taken-out-of-scanner-how-to-put-in-bids-format/17618

**Comment by finnlennartsson** [comment]
We stick to this convention, repeat/complemented scans will go under the same session as the first/original scan. 

For the NENAH we have currently only one session (i.e. not multiple sessions) => omit the "ses-ssID" level.

We have to make sure that we can handle repeat/complemented scans in the heudiconv step.

**Comment by yukaizou2015** [comment]
- [x] NENAH003 (run 2) #27

**Comment by yukaizou2015** [comment]
Still having issues with revisit scans. As a temporal solution, NENAHC033 (#113) and NENAH046 (#115) were re-organised into `/NENAHC033_newFunc` and `/NENAH046_newFunc` under `/rawdata`, to arrange the BOLD data scanned on different days into correct order of runID.

**Comment by finnlennartsson** [comment]
everything in /rawdata is now working
