### ISSUE TITLE
Update dMRI preprocessing script

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#3]
Update and establish a dMRI preprocessing routine.

Essentially follows the [BATMAN turorial](https://mfr.osf.io/render?url=https://osf.io/pm9ba/?direct%26mode=render%26action=download%26mode=render)

Uses the bash-script dMRI/preprocess.sh

**Comment by yukaizou2015** [comment]
CUDA 8.0 installed - see #13

**Comment by finnlennartsson** [comment]
CUDA is not starting
Add something to .bashrc?



(base) [fjl1f15@uos-15263 NENAH_BIDS_fjl1f15]$ bash code/NENAH-BIDS/dMRI/preprocess.sh NENAH014
dMRI preprocessing
Subject:       	NENAH014 
DWI (AP):	rawdata/sub-NENAH014/dwi/sub-NENAH014_dir-AP_run-1_dwi.nii.gz
DWI (PA):      	rawdata/sub-NENAH014/dwi/sub-NENAH014_dir-PA_run-1_dwi.nii.gz
Directory:     	derivatives/dMRI/sub-NENAH014 
code/NENAH-BIDS/dMRI/preprocess.sh   	NENAH014

dMRI preprocessing subject NENAH014

mrconvert: [100%] uncompressing image "rawdata/sub-NENAH014/dwi/sub-NENAH014_dir-AP_run-1_dwi.nii.gz"
mrconvert: [ERROR] output file "derivatives/dMRI/sub-NENAH014/preproc/sub-NENAH014_dir-AP_run-1_dwi.mif.gz" already exists (use -force option to force overwrite)
mrconvert: [ERROR] error creating image "derivatives/dMRI/sub-NENAH014/preproc/sub-NENAH014_dir-AP_run-1_dwi.mif.gz"
mrconvert: [100%] uncompressing image "rawdata/sub-NENAH014/dwi/sub-NENAH014_dir-PA_run-1_dwi.nii.gz"
mrconvert: [ERROR] output file "derivatives/dMRI/sub-NENAH014/preproc/sub-NENAH014_dir-PA_run-1_dwi.mif.gz" already exists (use -force option to force overwrite)
mrconvert: [ERROR] error creating image "derivatives/dMRI/sub-NENAH014/preproc/sub-NENAH014_dir-PA_run-1_dwi.mif.gz"
dwifslpreproc: 
dwifslpreproc: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
dwifslpreproc: 
dwifslpreproc: Generated scratch directory: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/
Command:  mrconvert /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwi_den_unr.mif.gz /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/dwi.mif -json_export /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/dwi.json
Command:  mrconvert /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/b0APPA.mif.gz /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/se_epi.mif
dwifslpreproc: Changing to scratch directory (/local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/)
dwifslpreproc: No slice encoding direction information present; assuming third axis corresponds to slices
Command:  mrconvert dwi.mif dwi_first_bzero.mif -coord 3 0 -axes 0,1,2
dwifslpreproc: Balanced phase-encoding scheme detected in SE-EPI series; volume 0 will be removed and replaced with first b=0 from DWIs
Command:  mrconvert se_epi.mif - -coord 3 1 | mrcat dwi_first_bzero.mif - se_epi_firstdwibzero.mif -axis 3
Command:  mrinfo dwi.mif -export_grad_mrtrix grad.b
Command:  mrconvert se_epi_firstdwibzero.mif topup_in.nii -strides -1,+2,+3,+4 -export_pe_table topup_datain.txt
Command:  topup --imain=topup_in.nii --datain=topup_datain.txt --out=field --fout=field_map.nii.gz --config=/local/scratch/software/fsl/6.0.4/etc/flirtsch/b02b0.cnf --verbose --iout=field_mag_unwarped
Command:  mrinfo dwi.mif -export_pe_eddy applytopup_config.txt applytopup_indices.txt
Command:  dwiextract dwi.mif -pe 0.0,-1.0,0.0,0.0436 - | mrconvert - dwi_pe_1.nii -strides -1,+2,+3,+4 -json_export dwi_pe_1.json
Command:  applytopup --imain=dwi_pe_1.nii --datain=applytopup_config.txt --inindex=1 --topup=field --out=dwi_pe_1_applytopup.nii --method=jac
Command:  mrconvert dwi_pe_1_applytopup.nii.gz dwi_pe_1_applytopup.mif -json_import dwi_pe_1.json
Command:  dwiextract dwi.mif -pe 0.0,1.0,0.0,0.0436 - | mrconvert - dwi_pe_2.nii -strides -1,+2,+3,+4 -json_export dwi_pe_2.json
Command:  applytopup --imain=dwi_pe_2.nii --datain=applytopup_config.txt --inindex=2 --topup=field --out=dwi_pe_2_applytopup.nii --method=jac
Command:  mrconvert dwi_pe_2_applytopup.nii.gz dwi_pe_2_applytopup.mif -json_import dwi_pe_2.json
Command:  mrcat dwi_pe_1_applytopup.mif dwi_pe_2_applytopup.mif - -axis 3 | dwi2mask - - | maskfilter - dilate - | mrconvert - eddy_mask.nii -datatype float32 -strides -1,+2,+3
Command:  mrconvert dwi.mif eddy_in.nii -strides -1,+2,+3,+4 -export_grad_fsl bvecs bvals -export_pe_eddy eddy_config.txt eddy_indices.txt
Command:  eddy_cuda9.1 --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --slspec=slspec.txt --out=dwi_post_eddy --verbose
dwifslpreproc: CUDA version of 'eddy' was not successful; attempting OpenMP version
Command:  eddy_openmp --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --slspec=slspec.txt --out=dwi_post_eddy --verbose

dwifslpreproc: [ERROR] eddy* --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --slspec=slspec.txt --out=dwi_post_eddy --verbose (app.py:197)
dwifslpreproc: [ERROR] Information from failed command:
dwifslpreproc:
               ============
               eddy_cuda9.1
               ============
               
               
               ===========
               eddy_openmp
               ===========
               EddyInputError:  Slice-to-vol is not yet implemented for the CPU version.
               Terminating program
               
               
               ============
               eddy_cuda9.1
               ============
               eddy_cuda9.1: error while loading shared libraries: libcublas.so.9.1: cannot open shared object file: No such file or directory
               
               
               ===========
               eddy_openmp
               ===========
               
               
dwifslpreproc:
dwifslpreproc: [ERROR] For debugging, inspect contents of scratch directory: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/
dwifslpreproc: Scratch directory retained; location: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-5TTXBS/
Pre-processing with mask generation, N4 biasfield correction, Normalisation, meanb0 generation and tensor estimation
dwiextract: [ERROR] cannot access file "dwi_den_unr_eddy.mif.gz": No such file or directory
dwiextract: [ERROR] error opening image "dwi_den_unr_eddy.mif.gz"
mrmath: [WARNING] existing output files will be overwritten
mrmath: [ERROR] no filename supplied to standard input (broken pipe?)
mrmath: [ERROR] error opening image "-"

Error: input image meanb0tmp not valid

qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
mrconvert: [ERROR] cannot access file "meanb0tmp_brain_mask.nii.gz": No such file or directory
mrconvert: [ERROR] error opening image "meanb0tmp_brain_mask.nii.gz"
rm: cannot remove ‘meanb0tmp*’: No such file or directory
dwibiascorrect: 
dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
dwibiascorrect: 
dwibiascorrect: Generated scratch directory: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwibiascorrect-tmp-QGCBP7/
Command:  mrconvert /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwi_den_unr_eddy.mif.gz /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwibiascorrect-tmp-QGCBP7/in.mif

dwibiascorrect: [ERROR] mrconvert /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwi_den_unr_eddy.mif.gz /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwibiascorrect-tmp-QGCBP7/in.mif (dwibiascorrect:50)
dwibiascorrect: [ERROR] Information from failed command:
dwibiascorrect:
                mrconvert: [ERROR] cannot access file "/local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwi_den_unr_eddy.mif.gz": No such file or directory
                mrconvert: [ERROR] error opening image "/local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwi_den_unr_eddy.mif.gz"
dwibiascorrect:
dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwibiascorrect-tmp-QGCBP7/
dwibiascorrect: Scratch directory retained; location: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwibiascorrect-tmp-QGCBP7/
Command:  dwiextract /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/dwi_preproc.mif.gz -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/mask.mif.gz -output median

dwinormalise: [ERROR] dwiextract /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/dwi_preproc.mif.gz -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/mask.mif.gz -output median (individual.py:66)
dwinormalise: [ERROR] Information from failed command:
dwinormalise:
              dwiextract: [ERROR] cannot access file "/local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/dwi_preproc.mif.gz": No such file or directory
              dwiextract: [ERROR] error opening image "/local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/dwi_preproc.mif.gz"
              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)
              mrmath: [ERROR] error opening image "-"
              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)
              mrstats: [ERROR] error opening image "-"
dwinormalise:
dwiextract: [ERROR] cannot access file "dwi_preproc_norm.mif.gz": No such file or directory
dwiextract: [ERROR] error opening image "dwi_preproc_norm.mif.gz"
mrmath: [WARNING] existing output files will be overwritten
mrmath: [ERROR] no filename supplied to standard input (broken pipe?)
mrmath: [ERROR] error opening image "-"
mrcalc: [ERROR] Could not interpret string "meanb0.mif.gz" as either an image path or a numerical value
mrcalc: [ERROR] As image: 
mrcalc: [ERROR] cannot access file "meanb0.mif.gz": No such file or directory
mrcalc: [ERROR] error opening image "meanb0.mif.gz"
mrcalc: [ERROR] As numerical value: 
mrcalc: [ERROR] error converting string "meanb0.mif.gz" to complex float (no valid conversion)
mrconvert: [ERROR] cannot access file "meanb0.mif.gz": No such file or directory
mrconvert: [ERROR] error opening image "meanb0.mif.gz"
mrconvert: [ERROR] cannot access file "meanb0_brain.mif.gz": No such file or directory
mrconvert: [ERROR] error opening image "meanb0_brain.mif.gz"
Visually check the meanb0_brain
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
dwi2tensor: [ERROR] cannot access file "dwi_preproc_norm.mif.gz": No such file or directory
dwi2tensor: [ERROR] error opening image "dwi_preproc_norm.mif.gz"
tensor2metric: [WARNING] existing output files will be overwritten
tensor2metric: [ERROR] cannot access file "dt.mif.gz": No such file or directory
tensor2metric: [ERROR] error opening image "dt.mif.gz"

**Comment by finnlennartsson** [comment]
Solution?

We have installed CUDA 8.0 (see #13)
So should make a soft link eddy_cuda that points to this?

See info in `dwifslpreproc`

The script will attempt to run the CUDA version of eddy; if this does not
     succeed for any reason, or is not present on the system, the CPU version
     will be attempted instead. By default, the CUDA eddy binary found that
     indicates compilation against the most recent version of CUDA will be
     attempted; this can be over-ridden by providing a soft-link "eddy_cuda"
     within your path that links to the binary you wish to be executed.

**Comment by yukaizou2015** [comment]
> Solution?
> 
> We have installed CUDA 8.0 (see #13)
> So should make a soft link eddy_cuda that points to this?
> 
> See info in `dwifslpreproc`
> 
> The script will attempt to run the CUDA version of eddy; if this does not
> succeed for any reason, or is not present on the system, the CPU version
> will be attempted instead. By default, the CUDA eddy binary found that
> indicates compilation against the most recent version of CUDA will be
> attempted; this can be over-ridden by providing a soft-link "eddy_cuda"
> within your path that links to the binary you wish to be executed.

Did you source `bashrc_fj1f15` before running `preprocess.sh`? Try adding this line to `bashrc_fj1f15`:

```
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
```
and commenting out
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-6.5/lib64
```

**Comment by finnlennartsson** [comment]
Updated with symbolic link to $FSLDIR/bin/eddy_cuda8.0 and put in path
Still not working!

This is extract from `dwifslproces`

Command:  eddy_cuda --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --slspec=slspec.txt --out=dwi_post_eddy --verbose
dwifslpreproc: CUDA version of 'eddy' was not successful; attempting OpenMP version
Command:  eddy_openmp --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --slspec=slspec.txt --out=dwi_post_eddy --verbose

dwifslpreproc: [ERROR] eddy* --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --slspec=slspec.txt --out=dwi_post_eddy --verbose (app.py:197)
dwifslpreproc: [ERROR] Information from failed command:
dwifslpreproc:
               =========
               eddy_cuda
               =========
               Reading images
               Performing volume-to-volume registration
               Running Register
               
               ...................Allocated GPU # 0...................
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 112.059, after update mss = 112.673
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 114.982, after update mss = 115.677
               Iter: 0, Total mss = 153.48
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 108.984, after update mss = 109.333
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 111.412, after update mss = 111.905
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 184.094, after update mss = 184.818
               Iter: 1, Total mss = 145.081
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 182.047, after update mss = 182.247
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 183.036, after update mss = 183.957
               Iter: 2, Total mss = 143.347
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 114.791, after update mss = 114.802
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 181.676, after update mss = 182.298
               Iter: 3, Total mss = 142.247
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 180.563, after update mss = 181.238
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 179.535, after update mss = 179.805
               Iter: 4, Total mss = 141.747
               Setting scan 0 as b0 shape-reference.
               Running sm.ApplyB0LocationReference
               Running sm.PolateB0MovPar
               Running Register
               Loading prediction maker
               Evaluating prediction maker model
               Checking for outliers
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 7.13804, after update mss = 7.15143
               Iter: 0, Total mss = 15.1272
               Loading prediction maker
               Evaluating prediction maker model
               Checking for outliers
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               Iter: 1, Total mss = 14.5155
               Loading prediction maker
               Evaluating prediction maker model
               Checking for outliers
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               Iter: 2, Total mss = 14.2841
               Loading prediction maker
               Evaluating prediction maker model
               Checking for outliers
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               Iter: 3, Total mss = 14.175
               Loading prediction maker
               Evaluating prediction maker model
               Checking for outliers
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               Iter: 4, Total mss = 14.0001
               Setting scan 75 as shell shape-reference for shell 0 with b-value= 1000
               Setting scan 65 as shell shape-reference for shell 1 with b-value= 2600
               Running sm.ApplyDWILocationReference
               Checking shell alignment along PE-direction (running PostEddyAlignShellsAlongPE)
               Aligning shells (running PostEddyAlignShells)
               Performing slice-to-volume registration
               Setting slice-to-volume order to 16
               Running Register
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 132.733, after update mss = 134.681
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 131.056, after update mss = 132.17
               Iter: 0, Total mss = 170.164
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 134.639, after update mss = 136.213
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 132.648, after update mss = 134.039
               Iter: 1, Total mss = 171.529
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.229, after update mss = 136.974
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 134.175, after update mss = 135.395
               Iter: 2, Total mss = 173.241
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.788, after update mss = 137.661
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 134.672, after update mss = 135.479
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 135.708, after update mss = 135.71
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.096, after update mss = 143.12
               Iter: 3, Total mss = 173.291
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 137.002, after update mss = 138.602
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 134.828, after update mss = 135.587
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.243, after update mss = 143.254
               Iter: 4, Total mss = 173.114
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 137.399, after update mss = 138.993
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 135.218, after update mss = 135.876
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.152, after update mss = 136.159
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.581, after update mss = 143.605
               Iter: 5, Total mss = 173.171
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 137.389, after update mss = 138.978
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 135.192, after update mss = 135.948
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.164, after update mss = 136.172
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.607, after update mss = 143.632
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 218.776, after update mss = 219.143
               Iter: 6, Total mss = 173.177
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 137.522, after update mss = 139.13
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 135.309, after update mss = 136.095
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.252, after update mss = 136.255
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.672, after update mss = 143.716
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 215.756, after update mss = 215.868
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 214.298, after update mss = 214.377
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 218.995, after update mss = 219.179
               Iter: 7, Total mss = 173.277
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 137.688, after update mss = 139.318
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 135.474, after update mss = 136.354
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.372, after update mss = 136.372
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.822, after update mss = 143.868
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 215.59, after update mss = 215.706
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 214.225, after update mss = 214.328
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 218.88, after update mss = 219.07
               Iter: 8, Total mss = 173.302
               Loading prediction maker
               Evaluating prediction maker model
               Calculating parameter updates
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 137.543, after update mss = 139.156
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 135.33, after update mss = 136.185
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 136.272, after update mss = 136.272
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 143.688, after update mss = 143.731
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 215.952, after update mss = 215.986
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 214.423, after update mss = 214.51
               EddyInternalGpuUtils::param_update: updates rejected
               EddyInternalGpuUtils::param_update: original mss = 219.036, after update mss = 219.127
               Iter: 9, Total mss = 173.343
               Running sm.ApplyB0ShapeReference
               matrix multiplication: problem with matrix inverse; suggest to use solve() instead
               EDDY:::  ECModels.h:::  void EDDY::ScanMovementModel::SetGroupWiseParameters(const Matrix&):  Exception �
               EDDY:::  ECScanClasses.cpp:::  void EDDY::ECScanManager::set_slice_to_vol_reference(unsigned int, EDDY::ScanType, int):  Exception thrown
               EDDY:::  ECScanClasses.h:::  void EDDY::ECScanManager::ApplyB0ShapeReference():  Exception thrown
               EDDY::: Eddy failed with message EDDY:::  eddy.cpp:::  EDDY::ReplacementManager* EDDY::DoSliceToVolumeRegistration(const EDDY::EddyCommandLineOptions&, unsigned int, bool, EDDY::ECScanManager&, EDDY::ReplacementManager*):  Exception �
               
               
               ===========
               eddy_openmp
               ===========
               EddyInputError:  Slice-to-vol is not yet implemented for the CPU version.
               Terminating program
               
               
               =========
               eddy_cuda
               =========
               
               
               ===========
               eddy_openmp
               ===========
               
               
dwifslpreproc:
dwifslpreproc: [ERROR] For debugging, inspect contents of scratch directory: /local/scratch/disk2/research/NENAH_BIDS_fjl1f15/derivatives/dMRI/sub-NENAH014/preproc/dwifslpreproc-tmp-WTQ05I/

**Comment by yukaizou2015** [comment]
Following the comment to edit the `slspect.txt` file for NENAH014
 - https://community.mrtrix.org/t/dwifslpreproc-eddy-slice-to-volume-correction-error/4203/4

**Comment by finnlennartsson** [comment]
dwifslpreproc -se_epi b0APPA.mif.gz -rpe_header -align_seepi -nocleanup \
        -topup_options " --iout=field_mag_unwarped" \
        -eddy_options " --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 " \
        -eddyqc_all eddy \
        dwi_den_unr.mif.gz \
        dwi_den_unr_eddy.mif.gz;

Change according to [mrtrix post](https://community.mrtrix.org/t/dwifslpreproc-eddy-slice-to-volume-correction-error/4203/2?u=finn)

dwifslpreproc -se_epi b0APPA.mif.gz -eddy_slspec  $studydir/sequences/slspec_NENAH_64_interleaved_slices.txt -align_seepi -nocleanup \
        -topup_options " --iout=field_mag_unwarped" \
        -eddy_options " --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 " \
        -eddyqc_all eddy \
        dwi_den_unr.mif.gz \
        dwi_den_unr_eddy.mif.gz;

**Comment by finnlennartsson** [comment]
Using soft link eddy_cuda -> eddy_cuda8.0 works

> dwifslpreproc -se_epi b0APPA.mif.gz -rpe_header -align_seepi -nocleanup
> -topup_options " --iout=field_mag_unwarped"
> -eddy_options " --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 "
> -eddyqc_all eddy
> dwi_den_unr.mif.gz
> dwi_den_unr_eddy.mif.gz;
> 
> Change according to [mrtrix post](https://community.mrtrix.org/t/dwifslpreproc-eddy-slice-to-volume-correction-error/4203/2?u=finn)
> 
> dwifslpreproc -se_epi b0APPA.mif.gz -eddy_slspec $studydir/sequences/slspec_NENAH_64_interleaved_slices.txt -align_seepi -nocleanup
> -topup_options " --iout=field_mag_unwarped"
> -eddy_options " --slm=linear --repol --mporder=16 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 "
> -eddyqc_all eddy
> dwi_den_unr.mif.gz
> dwi_den_unr_eddy.mif.gz;

**Comment by finnlennartsson** [comment]
Need to install N4

`dwibiascorrect: [ERROR] Could not find ANTS program N4BiasFieldCorrection; please check installation`

**Comment by yukaizou2015** [comment]
ANTs installed, try rerun `dwibiascorrect`

**Comment by finnlennartsson** [comment]
This is working now.
ANTs working
FSL's eddy_cuda working
