### ISSUE TITLE
Change patient identifier P$ into NENAH ID

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#4]

**Comment by yukaizou2015** [comment]
Harmonizing old (Pxxx) and new (NENAHxxx) naming. One subject will need to have one unique ID. To point out the repeat scan, use the session code in the BIDS (e.g. ses-1) to add subfolder under subject folder

**Comment by yukaizou2015** [comment]
To associate issues (specific patient ID) under milestone (All P -> NENAH)
