### ISSUE TITLE
Motion in DWIs between dir-AP and dir-PA in NENAH014

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#68]
There is severe motion between dir-AP_dwi and dir-PA_dwi in NENAH014.

Currently, I extracted first b0s from dir-AP and dir-PA without being able to inspect them for motion.

[qc.pdf](https://github.com/yukaizou2015/NENAH-BIDS/files/6516168/qc.pdf)

**Comment by yukaizou2015** [comment]
Scattered slice SHARD reconstruction for motion correction technique, see Christaens et al. ([link](https://www.sciencedirect.com/science/article/pii/S1053811920309228)) ([github](https://github.com/dchristiaens/shard-recon))

To run shard and mrtrix3, add these lines in `.bashrc`:

```
export PATH="/local/scratch/software/mrtrix3/bin:$PATH"
export PATH="/local/scratch/software/shard-recon/bin:$PATH"
```

**Comment by yukaizou2015** [comment]
Compare MRtrix + SHARD vs. EDDY (see B.A.T.M.A.N.) on this case

**Comment by finnlennartsson** [comment]
This subject is discarded
