### ISSUE TITLE
fMRIPrep

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#69]
- [Running fMRIPrep via Docker](https://fmriprep.org/en/stable/docker.html)

**Comment by yukaizou2015** [comment]
```
docker system prune -af
docker pull nipreps/fmriprep:latest
```
Run:
`docker run nipreps/fmriprep`

Incorporated into BIDS `DcmSourcedata_to_NiftiRawdata.sh` - [Line](https://github.com/yukaizou2015/NENAH-BIDS/blob/b8cd8030d17711004290bd2afed021a5a10cdc68/bids/DcmSourcedata_to_NiftiRawdata.sh#L126)

**Comment by finnlennartsson** [comment]
Not implemented any distortion correction?? 
https://fmriprep.org/en/0.5.3/workflows.html#module-fmriprep.workflows.fieldmap

Is the fmap not working??
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-3-direct-field-mapping

Is there a problem could that we have not updated the .json file with "Intended for field"
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#using-intendedfor-metadata

**Comment by yukaizou2015** [comment]
> Not implemented any distortion correction??
> https://fmriprep.org/en/0.5.3/workflows.html#module-fmriprep.workflows.fieldmap
> 
> Is the fmap not working??
> https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-3-direct-field-mapping
> 
> Is there a problem could that we have not updated the .json file with "Intended for field"
> https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#using-intendedfor-metadata

Phase-difference techniques are chosen for mapping the field (see [here](https://fmriprep.org/en/0.5.3/workflows.html#module-fmriprep.workflows.fieldmap) for details).
  - Use phase-difference for now, future (recommended) switches to Blip-up/blip-down or phase encoding polarity (used to developing human connectome project)

Each subject at each session contains one `phasediff.json` files under `fmap/`. Two things need to be done to update this file:

1. Add attribute "IntendedFor".
2. Update attribute "SliceTiming" (see issue #12).

**Comment by finnlennartsson** [comment]
**We may have multiple runs of . How do we chose which to use???**

The solution can be to use a `bids filter` which controls which files that should be used by `fmriprep`

https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep

**Comment by yukaizou2015** [comment]
> **We may have multiple runs of . How do we chose which to use???**
> 
> The solution can be to use a `bids filter` which controls which files that should be used by `fmriprep`
> 
> https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep

Now that head motion can be quickly evaluated without having to run fMRIprep, have made [running docker_run_fmriprep_noFS.sh as optional](https://github.com/yukaizou2015/NENAH-BIDS/tree/main/fMRI#optional-run-fmriprep-without-freesurfer). As default, run [segmentation.sh](https://github.com/yukaizou2015/NENAH-BIDS/blob/main/sMRI/segmentation.sh) first, followed by running [docker_run_fmriprep_postFS.sh](https://github.com/yukaizou2015/NENAH-BIDS/blob/main/fMRI/docker_run_fmriprep_postFS.sh)
