### ISSUE TITLE
Adding IntendedFor for fieldmaps in json

### ISSUE THREAD

**Issue by yukaizou2015** [sotnir/NENAH-BIDS#86]
Relate to #69. See [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#using-intendedfor-metadata) for an explanation why this attribute is important in fMRIPrep processing.

**Comment by yukaizou2015** [comment]
`phasediff.json` has been updated under `/rawdata`. Code and script for updating the files can be found at `/fMRI` under the slice_timing branch.

**Comment by finnlennartsson** [comment]
I suggest that we put these scripts in `/bids` since they and are operating on the BIDS `/rawdata` folder.
Indeed, everything that is working on the BIDS rawdata should be in the `/bids` folder. 

(Then we keep routines that generate data that go into `/derivatives` folder in their appropriate locations, like `/fMRI`, `/dMRI` or `sMRI`)

**Comment by yukaizou2015** [comment]
Could the following errors possibly be due to not specifying the full path?

```
bids-validator@1.8.1-dev.0

1: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
		./sub-NENAH002/fmap/sub-NENAH002_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH002/func/sub-NENAH002_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH004/fmap/sub-NENAH004_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH004/func/sub-NENAH004_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH005/fmap/sub-NENAH005_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH005/func/sub-NENAH005_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH007/fmap/sub-NENAH007_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH007/func/sub-NENAH007_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH007/fmap/sub-NENAH007_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH007/func/sub-NENAH007_task-rest_dir-AP_run-2_bold.nii.gz
		./sub-NENAH010/fmap/sub-NENAH010_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH010/func/sub-NENAH010_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH011/fmap/sub-NENAH011_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH011/func/sub-NENAH011_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH011/fmap/sub-NENAH011_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH011/func/sub-NENAH011_task-rest_dir-AP_run-2_bold.nii.gz
		./sub-NENAH012/fmap/sub-NENAH012_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH012/func/sub-NENAH012_task-rest_dir-AP_run-1_bold.nii.gz
		./sub-NENAH014/fmap/sub-NENAH014_acq-gre_run-1_phasediff.nii.gz
			Evidence: sub-NENAH014/func/sub-NENAH014_task-rest_dir-AP_run-1_bold.nii.gz
		... and 31 more files having this issue (Use --verbose to see them all).

	Please visit https://neurostars.org/search?q=INTENDED_FOR for existing conversations about this issue.
```

**Comment by yukaizou2015** [comment]
> Could the following errors possibly be due to not specifying the full path?
> 
> ```
> bids-validator@1.8.1-dev.0
> 
> 1: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
> 		./sub-NENAH002/fmap/sub-NENAH002_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH002/func/sub-NENAH002_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH004/fmap/sub-NENAH004_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH004/func/sub-NENAH004_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH005/fmap/sub-NENAH005_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH005/func/sub-NENAH005_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH007/fmap/sub-NENAH007_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH007/func/sub-NENAH007_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH007/fmap/sub-NENAH007_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH007/func/sub-NENAH007_task-rest_dir-AP_run-2_bold.nii.gz
> 		./sub-NENAH010/fmap/sub-NENAH010_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH010/func/sub-NENAH010_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH011/fmap/sub-NENAH011_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH011/func/sub-NENAH011_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH011/fmap/sub-NENAH011_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH011/func/sub-NENAH011_task-rest_dir-AP_run-2_bold.nii.gz
> 		./sub-NENAH012/fmap/sub-NENAH012_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH012/func/sub-NENAH012_task-rest_dir-AP_run-1_bold.nii.gz
> 		./sub-NENAH014/fmap/sub-NENAH014_acq-gre_run-1_phasediff.nii.gz
> 			Evidence: sub-NENAH014/func/sub-NENAH014_task-rest_dir-AP_run-1_bold.nii.gz
> 		... and 31 more files having this issue (Use --verbose to see them all).
> 
> 	Please visit https://neurostars.org/search?q=INTENDED_FOR for existing conversations about this issue.
> ```

Solved by replacing `sub-NENAH012/func/` with `func/`.
