### ISSUE TITLE
CUDA not working on Linux workstation

### ISSUE THREAD

**Issue by finnlennartsson** [sotnir/NENAH-BIDS#92]
Ran FSL's eddy but cannot invoke CUDA on Linux workstation

============
               eddy_cuda9.1
               ============
               eddy_cuda9.1: error while loading shared libraries: libcublas.so.9.1: cannot open shared object file: No such file or directory

**Comment by yukaizou2015** [comment]
CUDA 8.0 was installed - see [here](https://github.com/yukaizou2015/NENAH-BIDS/issues/13#issuecomment-757842120)

**Comment by finnlennartsson** [comment]
Yes, correct. We have to use eddy_cuda8.0
Following the advice on [FSL's eddyUsersGuide](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide) and making a symbolic 

For CUDA v8.0
`ln -sf ${FSLDIR}/bin/eddy_cuda8.0 ${FSLDIR}/bin/eddy_cuda`

sorted it!
